# Copied from https://github.com/rhysd/actionlint/blob/048c97d90b98b832450d3adf00fc7757b0ed9953/docs/usage.md#use-actionlint-on-github-actions
name: actionlint

on:
  pull_request:
    paths:
      - .github/workflows/*.yml

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # Disable git write access
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash
      - name: Check workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color
        shell: bash
- name: Setup mabl CLI
  # You may pin to the exact commit or the version.
  # uses: mablhq/setup-mabl-cli@39efbbbf128ff7f928f1012d287ce851eb40d001
  uses: mablhq/setup-mabl-cli@v1.3
  with:
    # (optional) The version of the mabl CLI to install
    version: # optional
    # (optional) DEPRECATED use workspace-id
    workspace: # optional
    # (optional) The id of the workspace to configure as default for the CLI
    workspace-id: # optional
